version: "3.8"

services:
  backend:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://morris_db:3306/morris_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    restart: unless-stopped
    depends_on:
      - morris_db
    networks:
      - network

  morris_db:
    container_name: morris_db
    image: mysql:latest
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=morris_db
      - MYSQL_USER=user
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - network
    restart: always

networks:
  network:
