version: "3.8"

services:
  backend:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/morris_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - network

  database:
    container_name: mysql_db
    image: mysql:latest
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=morris_db
      - MYSQL_USER=user
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - morris_mysql_volume:/var/lib/mysql
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    networks:
      - network
    restart: always

networks:
  network:

volumes:
  morris_mysql_volume: